apiVersion: v1
kind: PersistentVolume
metadata:
  name: loko-pv
spec:
  capacity: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeRelaimPolicy: Retain
  azureFile:
    secretName: <azure-secret>
    shareName: <name-from-azure>
    readOnly: false
